<a href="https://colab.research.google.com/github/Nahaeran/ai-for-ml-exercise/blob/main/week4/220922.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
cd /content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_02

# **Task1**
<hr>

In [38]:
import numpy as np
import pandas as pd

df = pd.read_csv('data/earthquakes.csv')

In [3]:
df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,sources,status,time,title,tsunami,type,types,tz,updated,url
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,",ci,",automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,",ci,",automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,",ci,",automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,",ci,",automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,",nc,",automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...

In [7]:
df.loc[3:10,['mag','magType','type']]

     mag magType        type
3   0.44      ml  earthquake
4   2.16      md  earthquake
5   2.61      md  earthquake
6   1.70      ml  earthquake
7   1.13      md  earthquake
8   0.92      md  earthquake
9   4.70      mb  earthquake
10  0.50      ml  earthquake

In [4]:
df.columns

Index(['alert', 'cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag',
       'magType', 'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources',
       'status', 'time', 'title', 'tsunami', 'type', 'types', 'tz', 'updated',
       'url'],
      dtype='object')

In [9]:
df.iloc[3:10,[8,9,21]]

    mag magType        type
3  0.44      ml  earthquake
4  2.16      md  earthquake
5  2.61      md  earthquake
6  1.70      ml  earthquake
7  1.13      md  earthquake
8  0.92      md  earthquake
9  4.70      mb  earthquake

In [20]:
df.loc[
    df.place.str.contains(r'Arizona$'),
    ['alert', 'mag', 'magType', 'title', 'tsunami', 'type']
]

,alert,mag,magType,title,tsunami,type
1062,NaN,1.23,ml,"M 1.2 - 7km SSW of Colorado City, Arizona",0,earthquake
3965,NaN,0.94,md,"M 0.9 - 7km WSW of Colorado City, Arizona",0,earthquake

In [16]:
df.mag.sort_values(ascending=False)[:10]

5263    7.5
837     7.0
4363    6.7
118     6.7
799     6.5
816     6.2
838     6.1
5323    6.1
9211    6.0
862     6.0
Name: mag, dtype: float64

# **Task2**
<hr>

In [39]:
del df['alert']
df.columns

Index(['cdi', 'code', 'detail', 'dmin', 'felt', 'gap', 'ids', 'mag', 'magType',
       'mmi', 'net', 'nst', 'place', 'rms', 'sig', 'sources', 'status', 'time',
       'title', 'tsunami', 'type', 'types', 'tz', 'updated', 'url'],
      dtype='object')

In [41]:
magColumn = df.pop('mag')
magColumn.head()

0    1.35
1    1.29
2    3.42
3    0.44
4    2.16
Name: mag, dtype: float64

In [42]:
magTypeColumn = df.pop('magType')
magTypeColumn.head()

0    ml
1    ml
2    ml
3    ml
4    md
Name: magType, dtype: object

In [43]:
df2 = pd.concat([magColumn, magTypeColumn], axis=1)
df2.head()

    mag magType
0  1.35      ml
1  1.29      ml
2  3.42      ml
3  0.44      ml
4  2.16      md