<a href="https://colab.research.google.com/github/Nahaeran/ai-for-ml-exercise/blob/main/week5/220929Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
cd /content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_04

/content/drive/MyDrive/Hands-On-Data-Analysis-with-Pandas-2nd-edition/ch_04

# Task3
<hr>

***practice filtering data***

In [4]:
import pandas as pd

weather = pd.read_csv('data/nyc_weather_2018.csv')
weather.head()

                  date datatype            station attributes  value
0  2018-01-01T00:00:00     PRCP  GHCND:US1CTFR0039       ,,N,    0.0
1  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0015       ,,N,    0.0
2  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0015       ,,N,    0.0
3  2018-01-01T00:00:00     PRCP  GHCND:US1NJBG0017       ,,N,    0.0
4  2018-01-01T00:00:00     SNOW  GHCND:US1NJBG0017       ,,N,    0.0

In [8]:
weather [
    (weather.datatype == "PRCP")
    & (weather.value > 0)
    & (weather.station.str.contains("S0007"))
]

                      date datatype            station attributes  value
788    2018-01-04T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    4.1
1044   2018-01-05T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,   18.0
1974   2018-01-09T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    0.5
2660   2018-01-12T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    0.5
2880   2018-01-13T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,   17.8
...                    ...      ...                ...        ...    ...
77317  2018-12-25T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    0.5
77536  2018-12-26T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    0.3
77974  2018-12-28T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    4.3
78191  2018-12-29T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,   25.9
78408  2018-12-30T00:00:00     PRCP  GHCND:US1NYNS0007       ,,N,    0.3

[175 rows x 5 columns]

In [9]:
weather.attributes.describe()

count     78780
unique       26
top        ,,N,
freq      34153
Name: attributes, dtype: object